language: node_js
git:
  depth: 10
node_js:
  - "0.12"
before_install:
  - npm install -g npm
install:
  - npm install grunt-cli -g
  - npm install
before_script:
  - grunt build
cache:
  directories:
    - node_modules
matrix:
  fast_finish: true
notifications:
  email:
    on_success: never
