sudo: false
language: node_js
git:
  depth: 10
node_js:
  - "0.12"
install:
  - npm install grunt-cli -g
  - npm install
before_script:
  - grunt test
matrix:
  fast_finish: true
notifications:
  email:
    on_success: never
